### PR TITLE
Fixed routing errors

### PR DESCRIPTION
**Pull request by audrism**

### CODE REVIEW

**Comment by audrism** [comment]
@dlomax64 still empty page :-( (btw, I am merging them to tryNew branch)

**Comment by dlomax64** [comment]
Are you getting any build errors? If so, try deleting `node_modules/` and `package-lock.json` then do `npm install --legacy-peer-deps`

**Comment by dlomax64** [comment]
Just tested tryNew with the above commands and the dev build works

**Comment by audrism** [comment]
Yes works for me as well
try run 
npm run start:prod

it listens on 8080, so you can run it as user


might the problem be that webpack does not work for prod?

const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');
nst webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');

**Comment by audrism** [comment]
cat config/webpack.prod.js 
const { merge } = require('webpack-merge');

const common = require('./webpack.common');

module.exports = merge(common, {
  mode: 'production',

  output: {
    filename: 'js/[name].[fullhash].js',
    chunkFilename: '[id].[fullhash].chunk.js'
  },

  optimization: {
    minimize: true
  }
});
a23f55da6dbe:~/swsc/DRE1>cat config/webpack.dev.js
const { merge } = require('webpack-merge');

const common = require('./webpack.common');

module.exports = merge(common, {
  mode: 'development',

  devtool: 'eval-source-map',

  output: {
    filename: 'js/[name].js',
    chunkFilename: '[id].chunk.js'
  },

  devServer: {
    contentBase: './client/public',
    historyApiFallback: true,
    stats: 'verbose', // none (or false), errors-only, minimal, normal (or true) and verbose
    hot: true
  },
});

**Comment by dlomax64** [comment]
When I try to run prod I get the error `no such file or directory, open '/etc/letsencrypt/live/worldofcode.org/privkey.pem'`

**Comment by dlomax64** [comment]
Okay, try merging my latest commits, then run `npm run build` then `npm run start:prod`. When we were previously running the website, the logic for running the production build wasn't working so it was compiling dynamically using `app.use(webpackHotMiddleware(compiler))` so that it updates changes on the fly. Since we want to deploy a production version, I think the proper way is to build it first and then serve a static version.

**Comment by audrism** [comment]
Even though the right command is issued for:
https://worldofcode.org/lookupresult?sha1=00b31262da21c4f57d5b207372b6ded0bb332911&type=blob

nothing shows up (here is server log and if I rubn it on the server it returns content):
ssh -T da5 << EOF
  echo "00b31262da21c4f57d5b207372b6ded0bb332911" | $HOME/lookup/showCnt blob
EOF

**Comment by dlomax64** [comment]
Looking into it

**Comment by dlomax64** [comment]
Fixed it. The module we were using to display the contents changed syntax so it was a really simple fix

**Comment by dlomax64** [comment]
I posted an issue on lookup (https://github.com/ssc-oscar/lookup/issues/34) that is causing FastGraph to not work FYI

**Pull request merged**
