### PR TITLE
chore: add backend routes to readme

### PR DESCRIPTION
**Pull request by px1624**

### CODE REVIEW

**Comment by audrism** [comment]
@px1624 Michael, I wonder if it would be possible to have 'ssh da4' obtained from the environment(e.g. REMOTE_CMD)? when I run a production version, it runs as root from the docker, but I need to ssh as certain user to da4, also, potentially to da5, not to da4.

**Comment by px1624** [comment]
> @px1624 Michael, I wonder if it would be possible to have 'ssh da4' obtained from the environment(e.g. REMOTE_CMD)? when I run a production version, it runs as root from the docker, but I need to ssh as certain user to da4, also, potentially to da5, not to da4.

@audrism No problem, I can make it pull ssh command from the environment variable. Is DRE_REMOTE_CMD a suitable name for the variable?

**Comment by audrism** [comment]
@px1624 I made PR you reviewed: using the config, is it possible to override it via DRE_REMOTE_CMD?

**Comment by px1624** [comment]
@audrism override implemented in [this PR](https://github.com/ssc-oscar/DRE/pull/20)

**Pull request merged**
